### PR TITLE
net-im/gtkcord4: remove package

### PR DESCRIPTION
**Pull request by gentoo-setan**
It's been renamed to dissent and it's at version 0.25 now.
https://github.com/diamondburned/dissent/
This is badly outdated and I think should be removed

### CODE REVIEW

**Comment by stkw0** [comment]
Thank you very much for the report. 
It can not be removed directly. First it has to be masked in order to make users aware of the removal and being able to give them time to adapt, change to an alternative or so. 

Given you are the current maintainer for the package, do you want to handle it @Schievel1?

**Comment by Schievel1** [comment]
Yes, I agree. I couldn't update it anymore because it didn't build for me with portage. 

Since this is ::guru and not ::gentoo, do we still need to stick to the 30 day masking procedure?

**Comment by antecrescent** [comment]
> Since this is ::guru and not ::gentoo, do we still need to stick to the 30 day masking procedure?

Yes, we also stick to in ::guru.

**Comment by Schievel1** [comment]
I just pushed 4e513c2. The removal is at the end of August because of my vacation in between.

**Pull request closed without merging**
