### PR TITLE
gui-libs/xdg-desktop-portal-hyprland: Added patch for clang, introduced check for >=clang:17

### PR DESCRIPTION
**Pull request by Fuchskaute**
The build issues with clang have been resolved upstream in the following commits:
https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/54b5467ec12fb115b537e0c86256226474edf8bb
https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/f9461b0b7d3071347390feee534638555ff76c7d

I combined the last 3 commits into a patch and added it to the ebuild for 1.1.0 if the user is using clang.
I also added a check for >=clang-17.0.1 as it failed to build with clang-16.0.6 while testing in a chroot.

I would be happy about any feedback or helping with further testing that is required.

### CODE REVIEW

**Comment by stkw0** [comment]
I don't understand the reasoning behind having a pkg_setup with those checks instead of having a USE flag like "clang" and having something like 
```
clang? ( >=sys-devel/clang-17.0.1 )
!clang ( >=sys-devel/gcc-13.0.0 )
```

**Comment by stkw0** [comment]
I don't think it's a big issue, but I don't understand the reason, although I believe if someone wrote it that way it is because there is a reason. In general, it's better to fail as soon as possible. Moving those checks to BDEPEND could make life easier for end users as portage will automatically pull the required compiler without the need for the user to run portage, wait while it resolve the dependencies, then have a failure right after starting to emerging packages and then having to manually installing the required compiler and running portage again.

Could you fixup the last commit so the history is cleaner?

**Comment by Fuchskaute** [comment]
If you could define what you mean by fixup gladly! Also I just got GURU commit access myself, so sorry for creating a PR here I got lucky someone actually checked.

**Comment by micielski** [comment]
Commited!

> I don't understand the reasoning behind having a pkg_setup with those checks instead of having a USE flag like "clang" and having something like
> 
> ```
> clang? ( >=sys-devel/clang-17.0.1 )
> !clang ( >=sys-devel/gcc-13.0.0 )
> ```
Well, the thing you are proposing isn't the best (depending on a compiler doesn't mean that the ebuild will compile with it, which is why there is a check in pkg_setup), but you're correct. There should be a dependency for a newer version of gcc/clang, which I've added a few hours ago. Thank you for keeping an eye on me.

**Comment by Fuchskaute** [comment]
Closed by the following commit https://github.com/gentoo/guru/commit/2487eafda90ed51e414083ee0a11e71918cbdb18

**Comment by Fuchskaute** [comment]
Did I make a big mistake

**Comment by micielski** [comment]
> Did I make a big oopsie

Not really, Larry will close this issue anyway, so it doesn't matter whether you leave it open or closed :D

**Comment by Fuchskaute** [comment]
Alright, thank you for the info! I already thought it would be auto-closed but wasn't so I was unsure

**Comment by stkw0** [comment]
> Commited!
> 
> > I don't understand the reasoning behind having a pkg_setup with those checks instead of having a USE flag like "clang" and having something like
> > ```
> > clang? ( >=sys-devel/clang-17.0.1 )
> > !clang ( >=sys-devel/gcc-13.0.0 )
> > ```
> 
> Well, the thing you are proposing isn't the best (depending on a compiler doesn't mean that the ebuild will compile with it, which is why there is a check in pkg_setup), but you're correct. There should be a dependency for a newer version of gcc/clang, which I've added a few hours ago. Thank you for keeping an eye on me.

I don't know if I understood you correctly. The check you are referring can be done by portage directly. In that regard, making the check on pkg_setup don't seem to bring any benefit. I mean, this
```
if [[ $(clang-major-version) -lt 17 ]] ; then
	die "XDPH-1.1.0 requires >= sys-devel/clang-17.0.1 to build"
fi
```
is strictly equivalent to
`BDEPEND=">=sys-devel/clang-17.0.0"` 
afaik, with the only difference that in the second case portage will try to resolve that dependency if possible and if not it will fail when resolving the dependencies instead. Making the check on pkg_setup tricks portage into thinking that the dependencies have been resolved when it may not be the case.

**Comment by stkw0** [comment]
> If you could define what you mean by fixup gladly! Also I just got GURU commit access myself, so sorry for creating a PR here I got lucky someone actually checked.

when making a PR request it may be common that additional small changes are made. Those changes, if small, maybe don't need to have a commit by itself. One common approach is to fixup the commits. I am bad explaining this kind of things but you can search for more info, sry. In practice what I do is to run `git rebase -i HEAD~N` where N is the number of commits and then fixup the commits that have small or trivial changes. The interactive menu already shows a good explanation of the different options.

**Comment by Fuchskaute** [comment]
> > If you could define what you mean by fixup gladly! Also I just got GURU commit access myself, so sorry for creating a PR here I got lucky someone actually checked.
> 
> when making a PR (and only on PR ) request it may happen that additional small changes are made. Those changes, if small, maybe don't need to have a commit by itself. One common approach is to fixup the commits. I am bad explaining this kind of things but you can search for more info, sry. In practice what I do is to run `git rebase -i HEAD~N` where N is the number of commits and then fixup the commits that have small or trivial changes. The interactive menu already shows a good explanation of the different options.

That explanation was already very helpful, thank you!

**Comment by micielski** [comment]
> I don't know if I understood you correctly. The check you are referring can be done by portage directly. In that regard, making the check on pkg_setup don't seem to bring any benefit. I mean, this
> 
> ```
> if [[ $(clang-major-version) -lt 17 ]] ; then
> 	die "XDPH-1.1.0 requires >= sys-devel/clang-17.0.1 to build"
> fi
> ```
> 
> is strictly equivalent to `BDEPEND=">=sys-devel/clang-17.0.0"` afaik, with the only difference that in the second case portage will try to resolve that dependency if possible and if not it will fail when resolving the dependencies instead. Making the check on pkg_setup tricks portage into thinking that the dependencies have been resolved when it may not be the case.

Let's say that I've upgraded Clang from 16 to 17. For a brief moment, I'll have two different versions of that same compiler until I do `emerge --depclean` which will remove the old version, and so there's no guarantee that I'll immediately use the new version of Clang (and I could still overwrite this with yet another compiler in `package.env`, for example with `dev-lang/tcc`).
Here's an example of the same check in [::gentoo](https://github.com/gentoo/gentoo/blob/1cf7e6d4fddfa1868718baf2ac3263782a0b6b74/dev-libs/botan/botan-3.1.1.ebuild#L69C1-L77C4)
Does it make sense? If not, maybe let's hop on IRC? I'm `micielski` on Libera (well, we've already chatted there, but just in case x) )

**Comment by Fuchskaute** [comment]
For further reference here is the same check I introduced in the Hyprland ebuild on ::gentoo.

https://github.com/gentoo/gentoo/blob/1cf7e6d4fddfa1868718baf2ac3263782a0b6b74/gui-wm/hyprland/hyprland-0.29.1.ebuild#L81

**Comment by stkw0** [comment]
I see, that makes sense. Thank you very much for your explanation! :)

**Pull request closed without merging**
