### PR TITLE
Update repoman.yml

### PR DESCRIPTION
**Pull request by scardracs**
@AndrewAmmerlaan something like that

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
I think we might be able to do this faster and easier by querying GitHub for which version is the latest and then downloading that. Something like this might work:
https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8
https://github.com/marketplace/actions/fetch-latest-release

Alternatively we could just `git sync` the `gentoo/portage` repository and then use `git tag | grep  repoman- | sed 's/repoman-//g'` to find the latest version and switch to that using e.g. `git checkout tags/repoman-3.0.3 -b repoman-3.0.3`

**Comment by scardracs** [comment]
> I think we might be able to do this faster and easier by querying GitHub for which version is the latest and then downloading that. Something like this might work:
> https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8
> https://github.com/marketplace/actions/fetch-latest-release
> 
> Alternatively we could just `git sync` the `gentoo/portage` repository and then use `git tag | grep repoman- | sed 's/repoman-//g'` to find the latest version and switch to that using e.g. `git checkout tags/repoman-3.0.3 -b repoman-3.0.3`

Using sed seems promising, let me take some checks :)

**Comment by scardracs** [comment]
Looks like these: https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8 doesn't work for mirrored github repos

**Comment by scardracs** [comment]
Using my way requires to change emerge --sync from rsync to git, so it is a no go (too much effort for what we really need)

**Comment by AndrewAmmerlaan** [comment]
Fixed in: https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=292e03dc22ddc1d5a3bf143d311344f8cc0d9f75

The repoman check should now always use the latest version :)

**Comment by scardracs** [comment]
> Fixed in: https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=292e03dc22ddc1d5a3bf143d311344f8cc0d9f75
> 
> The repoman check should now always use the latest version :)

Looks promising. Have you already tested it?

**Comment by AndrewAmmerlaan** [comment]
> Looks promising. Have you already tested it?

Yes, I have tested this in this PR first: https://github.com/gentoo/guru/pull/49

**Comment by scardracs** [comment]
> > Looks promising. Have you already tested it?
> 
> Yes, I have tested this in this PR first: https://github.com/gentoo/guru/pull/49

Gg!

**Pull request closed without merging**
