### PR TITLE
media-libs/amdvlk: update to 2024.4.2

### PR DESCRIPTION
**Pull request by Username404-59**
Updates the license path patch ~~& adds [yet another patch](https://github.com/GPUOpen-Drivers/pal/pull/103) to fix compilation issues~~

The [wrong reference one should get fixed in >=2024.4.2](https://github.com/GPUOpen-Drivers/pal/pull/102#issuecomment-2444002459).

### CODE REVIEW

**Comment by stkw0** [comment]
CC: @RarogCmex (I saw you made a commit for the update to 2024.4.1 but this PR also changes some other things that may be worth looking at)

**Comment by RarogCmex** [comment]
@stkw0 To be honest: I am not able to maintain all the changes because of a hard undergrade curriculum in Financial University Under Russian Government (hell, yeah), but I will do something when I get some free time. I update amdvlk-bin because it takes only around 15 minutes of my mere live.

**Comment by stkw0** [comment]
Yeah no problem. I would have merged this myself but seems a more delicate thing and I don't even have the hardware to test it. Lots of encouragement with the uni!

@Username404-59 I don't know if you are aware, but you can register on GURU (see https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors) and commit directly to the dev branch. You could even help to co-maintain amdvlk if you are interested :)

**Comment by Username404-59** [comment]
> @Username404-59 I don't know if you are aware, but you can register on GURU (see https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors) and commit directly to the dev branch. You could even help to co-maintain amdvlk if you are interested :)

I'll maybe look into it 👀

**Comment by Username404-59** [comment]
Updated it to 2024.4.2 which shouldn't need the 2 patches anymore

**Comment by Username404-59** [comment]
> I encourage you to register as a contributor. Is this kind of things that may seem complicated but once it's done one realizes it was far more trivial was thought.

Yep made a request [here](https://bugs.gentoo.org/945886)

**Comment by RarogCmex** [comment]
@Username404-59 I have just merged your changes manually so no time is wasted.
Can't wait for your maintainership.
Good luck!

**Pull request closed without merging**
