### PR TITLE
licenses: add MIT-fpdf

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**
For https://github.com/gentoo/guru/pull/221

### CODE REVIEW

**Comment by stkw0** [comment]
It should be fpdf. If it's not an MIT license why should it be called "MIT-fpdf"?

**Comment by antecrescent** [comment]
This commit should be part of https://github.com/gentoo/guru/pull/221. There's no need for an additional PR.

**Comment by vitaly-zdanevich** [comment]
ok

**Comment by eli-schwartz** [comment]
> It should be fpdf. If it's not an MIT license why should it be called "MIT-fpdf"?

To be fair, it does appear to be an MIT derivative. So the name doesn't come out of nowhere.

**Pull request closed without merging**
