### PR TITLE
Openstack

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
@prometheanfire what do you think?

**Comment by prometheanfire** [comment]
What is the end goal for this?  the packages still need to be maintained

**Comment by Alessandro-Barbieri** [comment]
Would you like to continue maintaining them here? Or have you completely given up?

**Comment by prometheanfire** [comment]
Gentoo tends to deprecate stable python faster than what upstream openstack targets (they are removing py37 soon iirc).  Upstream tends to stick to what is included in debian and ubuntu.  The python team won't let me package openstack without their oversight.

**Comment by Alessandro-Barbieri** [comment]
@prometheanfire I've restored the ebuilds here. Feel free to make any changes, I'll improve documentation building

**Comment by prometheanfire** [comment]
I think, if you want to keep it around, it is best put into a overlay.  thanks for the interest though.

**Pull request closed without merging**
