### PR TITLE
Bump mangohud to 0.7.2 with build fixes, drop 0.7.1

### PR DESCRIPTION
**Pull request by nillerusr**

### CODE REVIEW

**Comment by pastalian** [comment]
Maintainers: @AdelKS @MrDuartePT

**Comment by MrDuartePT** [comment]
I will not accept this for a simple reason. I already have a working copy but I need spdlog to be updated frist.

https://github.com/gentoo/gentoo/pull/36433

**Comment by nillerusr** [comment]
@MrDuartePT anyway please add mangoplot use flag. I don't wanna see garbage in my system like matplotlib

**Comment by MrDuartePT** [comment]
> @MrDuartePT anyway please add mangoplot use flag. I don't wanna see garbage in my system like matplotlib for 1 small python script

Done it on dev now!

**Pull request closed without merging**
