### PR TITLE
www-plugins/firefoxpwa: add 2.10.1

### PR DESCRIPTION
**Pull request by filips123**

### CODE REVIEW

**Comment by stkw0** [comment]
I see you are making contribution from time to time. Just in case you find it of interest, you can join GURU which would allow you to commit directly to ::guru repository without the need of opening a PR. See https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors for more information

**Comment by filips123** [comment]
These PRs are automated with GitHub Actions from my repository. I initially wanted to directly submit commits to GURU, however, someone said that it's not appropriate [to do automated commits or give access to GURU to GitHub Actions](https://bugs.gentoo.org/914658#c1) for security reasons, so I decided to submit PRs instead as that's better from a security perspective. I hope that's fine.

**Comment by stkw0** [comment]
Ah, yes. Sorry, I read that bug long ago but forgot about it.

**Comment by stkw0** [comment]
Seems it has been already merged: https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=20697e133fdeea4e9c882490769df96e80ad29c2

**Comment by filips123** [comment]
Ok, I'll close this PR.

**Pull request closed without merging**
