### PR TITLE
http://neil.franklin.ch/Projects/dphys-swapfile

### PR DESCRIPTION
**Pull request by ShorTie8**
Add a ebuild so a user can add a swap file.
Author Neil Franklin, last modification 2006.09.15
Developed in the Physics Department.

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
This looks good :+1: 

We don't really do PRs in ::guru though, you can just commit this yourself by filling an access request on bugzilla. The guide is here: https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors

**Comment by ShorTie8** [comment]
Ok, I change the Keywords to  KEYWORDS="~amd64 ~arm ~arm64 ~x86"
How do I resubmit it ?? 
Tried filling a bug, https://bugs.gentoo.org/761133
Didn't do much to help.
So I thought I might try this way, lol.

**Comment by AndrewAmmerlaan** [comment]
> Ok, I change the Keywords to KEYWORDS="~amd64 ~arm ~arm64 ~x86"
> How do I resubmit it ??
> Tried filling a bug, https://bugs.gentoo.org/761133
> Didn't do much to help.
> So I thought I might try this way, lol.

You can open an access request bug on bugzilla under the GURU product, then someone will give you commit access to the repository. Next you can just, configure git as described, add your ebuild and run `repoman ci` and `git push`.

See here: https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors

**Comment by ShorTie8** [comment]
Now what if I can ask, to get this included ??

**Comment by AndrewAmmerlaan** [comment]
> Now what if I can ask, to get this included ??

Just set up the GURU git repository as described in the guide here: https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors and push your commit to the dev branch: `repoman ci && git push`. It will then be merged to the master branch by one of the Trusted Contributors

**Comment by ShorTie8** [comment]
More BS.
I thought this was suppose to be a stepping stone to ::gentoo ??
As said by others.
"<@NeddySeagoon> ShorTie: Yeah. I'm not a great fan of GURU. You may as well proxy contribute to the ::gentoo repo"
My github credentials are good enough for a pull request.
Good enough for repoman to do it's thing.
Why is that not enough ??

What are these ' Trusted contributors' gonna do that repoman didn't ??
Are they gonna actually emerge it and use it ??
Or just gaze at it in for a minute or 2 ??
Curious minds want to know.

Don't see why it can't be just included.
You already have a bug page for things.
Or you don't Trust Us to supply a working paackage ??

I think using the bugs, you could let The peeps that use it sort out weather it works or not.
And maybe then, if you get to many 'It don't F'n work's', then you remove it.
And if you could monitor likes some way, After so many it gets upgraded to ::gentoo.

Don't know
Got me.
Seems like an awfull lot of BS to get sumfin from 2004, that every other distro has, into Gentoo.
Just more "Waste Days and Wasted Nights" with Gentoo.
To me, at least it's just play for me, lol.

**Comment by AndrewAmmerlaan** [comment]
I think we are misunderstanding each other.

> Don't see why it can't be just included.

I'm not saying that we cannot add this, I'm saying that you can add it yourself. You don't need me, or the Pull Request, you can commit directly to the repository.

> Or you don't Trust Us to supply a working paackage

Quite the opposite actually, we do trust you, which is why in ::guru you can commit things yourself directly to the dev branch.

> What are these ' Trusted contributors' gonna do that repoman didn't ??
> Are they gonna actually emerge it and use it ??
> Or just gaze at it in for a minute or 2 ??

The only function of the Trusted Contributors is to make sure that there is no malware or other things that might be harmful in ::guru. So in general, yes, we just gaze at it for a minute or two, and then push it to the master branch.

**Comment by ShorTie8** [comment]
Guess I'm Cornfuzed about why you can't just finalize the pull request.
Like any other github site would.

I Really, Really, Apricate all your help so far.
But since this is like a one time thing, or turning into.
(Can't see the Pi Foundation making many more changes .. :/~)
I'll leave you with a quote for yucks,
"<@NeddySeagoon> ShorTie: Yeah. I'm not a great fan of GURU. You may as well proxy contribute to the ::gentoo repo"

**Comment by AndrewAmmerlaan** [comment]
> Guess I'm Cornfuzed about why you can't just finalize the pull request.
> Like any other github site would.

Because, as I mentioned in my first reply, we don't usually work with Pull Requests, or with GitHub for that matter. It's not like I can just press the "merge" button here, because this is just a mirror. The actual repository is here: https://gitweb.gentoo.org/repo/proj/guru.git/ and anyone who requests for access on bugzilla can commit to it directly.

**Comment by ShorTie8** [comment]
So I guess the pull request button is a Joke then ??

**Comment by ShorTie8** [comment]
I think You guys got your Master mixed up then.

**Comment by AndrewAmmerlaan** [comment]
> So I guess the pull request button is a Joke then ??

No, not a joke, it does come in handy every now and then when checking if large scale changes will break anything before applying those changes. To actually apply any commits you just push them to: https://gitweb.gentoo.org/repo/proj/guru.git/ after applying for access.

**Comment by ShorTie8** [comment]
Personally, I think You guys got your Master's Mixed Up, should be more like,
https://github.com/gentoo/guru --> https://gitweb.gentoo.org/repo/proj/guru.git/
For a simple pull request, to function.

If this thing is gonna differ from any of the other Methods.

**Comment by ShorTie8** [comment]
I quoted you, but didn't say from who or where.
Hope it is ok.
https://forums.gentoo.org/viewtopic-p-8574771.html#8574771

**Comment by scardracs** [comment]
@ShorTie8 i think you have misunderstood what @AndrewAmmerlaan tried to say. This repo is just a mirror, nothing more. Contributions are welcome, but you have to set gitweb as your point for push your ebuilds because PRs here won't be added, nothing more, nothing less than that. It's not because we don't want your contribution, it's because we on guru work in that way

**Comment by scardracs** [comment]
After saying that, please commit your things to gitweb and close this PR because, as said, it won't be merged until you move it to gitweb

**Comment by ShorTie8** [comment]
Dude, there is no real maintaining of this.
It has been around for years and years.
Gentoo is like the only OS that does NOT offer it.
What a dis-service to the Gentoo community, imho.
For me, your laying out far to many "things I must do" for such a simple thing.

**Comment by ixti** [comment]
I was not proposing to become a maintainer of the dphys-swapfile. I was merely proposing to become a somewhat proxy-maintainer of an ebuild, as it's required by this project rules.

I was able to find this software in Debian and its derivatives. Debian package has 2 maintainers. Ubuntu package has its maintainer on top of Debian's. The idea of GURU is to provide an official overlay with packages maintained by the community. That means if some user will have an issue with the package — maintainer will be responsible to fix the package ebuild (e.g., it might be conflicting with other ebuilds) or work with the upstream to resolve the issue.

GURU is just an overlay project with its rules. It's not enabled by default. You have to enable it just like any other overlay. Thus, if you don't agree with GURU contributing regulations, the best is to create your overlay:

``` bash
eselect repository create ShorTie8-overlay
```

See Also: https://wiki.gentoo.org/wiki/Eselect/Repository

**Comment by ixti** [comment]
@ShorTie8 @AndrewAmmerlaan if there's no desire in following GURU requirements and no willingness to maintain the ebuild, can we close this PR?

**Pull request closed without merging**
