### PR TITLE
Update uxplay-1.56.ebuild

### PR DESCRIPTION
**Pull request by roodyfluff**
Fixed :
missing gst-plugins-good libs
missing ffmpeg vaapi

### CODE REVIEW

**Comment by p5k369** [comment]
Hey @roodyfluff, if you want to contribute to guru overlay check out this page: [Information for Contributors](https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors). Also make sure you commit to dev branch.

**Comment by Schievel1** [comment]
You can keep this PR tough, I will review and merge it, if you don't want to sign up for the guru. 
This is looking fine already, but please change the target branch to guru::dev.
Thanks.

**Comment by tastytea** [comment]
Can someone close this? The version in ::guru is 1.63 now. 😊

**Comment by stkw0** [comment]
I thought this was already fixed but seems the package was still broken. As the changset was small I commit them directly.

**Pull request closed without merging**
