### PR TITLE
https://bugs.gentoo.org/910572

### PR DESCRIPTION
**Pull request by Bratzmeister**
fixed rename from dev-util/cmake to dev-build/cmake

### CODE REVIEW

**Comment by Bratzmeister** [comment]
also see dd1fefe6428552b0263aa3b23259c0a9ae40c792

**Comment by CyberTailor** [comment]
We can't apply your commits without `Signed-off-by`

**Comment by CyberTailor** [comment]
This needed urgent action, so I had to fix this tree-wide and this PR is no longer relevant

**Comment by mgorny** [comment]
Thanks anyway.

**Pull request closed without merging**
