### PR TITLE
🔥 dev-util/bazelisk: moved to ::gentoo

### PR DESCRIPTION
**Pull request by Jamim**
_Hello @ezzieyguywuf,_

**Bazelisk** `1.20` is now [available](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-build/bazelisk) in the `::gentoo` tree, so it's safe to drop it.

_Best regards!_

### CODE REVIEW

**Comment by ezzieyguywuf** [comment]
> _Hello @ezzieyguywuf,_
> 
> **Bazelisk** `1.20` is now [available](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-build/bazelisk) in the `::gentoo` tree, so it's safe to drop it.
> 
> _Best regards!_

this is great news, thanks for the ping! I'll make some time this week to drop it from guru.

**Comment by antecrescent** [comment]
> this is great news, thanks for the ping! I'll make some time this week to drop it from guru.

I'm merging @Jamim's commit early to not have a duplicate package in GURU needlessly violate the regulations.

**Comment by antecrescent** [comment]
@Jamim You've contributed a few times to GURU now. Have you thought about [requesting access to the server](https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors) to contribute directly yet?
By contributing the "official way", you get more eyes on your changes, your changes get merged quicker into `main` and it's generally less work for all participants ;)

**Comment by Jamim** [comment]
@antecrescent not yet. I hope I'll be able to do so in the near future.

**Pull request closed without merging**
