### PR TITLE
dev-util/mh: add 1.4.1, drop 1.0.3

### PR DESCRIPTION
**Pull request by oz123**
Bug: https://bugs.gentoo.org//945210

### CODE REVIEW

**Comment by pastalian** [comment]
> Bug: https://bugs.gentoo.org/912373

Wrong bug?

**Comment by oz123** [comment]
Yep. Wrong. Fixed now.

**Comment by pastalian** [comment]
Thanks. You have access to the dev branch, right?

**Comment by oz123** [comment]
> Thanks. You have access to the dev branch, right?

I am not aware of someone explictly giving me access to the dev branch. Am I supposed to have it?

**Comment by pastalian** [comment]
Looking at this bug, I think so.
https://bugs.gentoo.org/803419

**Comment by oz123** [comment]
Seems that my access is expired:

```
~/Software/gentoo/guru/dev-util/mh[±|dev → origin ↑1 ✓|] $ git push
ERROR: Permission to gentoo/guru.git denied to oz123.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by oz123** [comment]
The commit is on the dev branch. Closing.

**Pull request closed without merging**
