### PR TITLE
Hyprland needs 2 files under /usr/share/protocols

### PR DESCRIPTION
**Pull request by ignamartinoli**
Closes: https://bugs.gentoo.org/904299

### CODE REVIEW

**Comment by MrRoy** [comment]
You need to add:
```
PATCHES=(
   "${FILES}/0.24.1-meson.patch
)
```
to the ebuild so the patch is actually applied
See: https://devmanual.gentoo.org/ebuild-writing/functions/src_prepare/epatch/index.html

Also, can you test this to make sure it works for you? You can try it by running:
`# ebuild hyprland-0.24.1-r1.ebuild merge`

**Comment by ignamartinoli** [comment]
Alright. I'm not that good at *git*. I made the change to the file and ran `git add hyprland-0.24.1-r1.ebuild`

If I'm not wrong now I have to run `git commit --amend`. To push it to this PR, what do I need to run?

**Comment by ignamartinoli** [comment]
I guess I found out by trial and error eheh

**Comment by ignamartinoli** [comment]
I tried to test the patch but got an error

```
sicro@sicro ~/git/guru/gui-wm/hyprland $ doas ebuild hyprland-0.24.1-r1.ebuild merge
Appending /home/sicro/git/guru to PORTDIR_OVERLAY...
!!! Fetched file: hyprland-0.24.1-r1.tar.gz VERIFY FAILED!
!!! Reason: Insufficient data for checksum verification
!!! Got:
!!! Expected: BLAKE2B BLAKE2S MD5 RMD160 SHA1 SHA256 SHA3_256 SHA3_512 SHA512 WHIRLPOOL
```

**Comment by N-R-K** [comment]
> I tried to test the patch but got an error

The manifest needs to be updated as well. `ebuild [insert .ebuild] manifest`.

**Comment by ignamartinoli** [comment]
When I try to build I get the following error

```
>>> Preparing source in /var/tmp/portage/gui-wm/hyprland-0.24.1-r1/work/Hyprland-0.24.1 ...
 [32m*[0m Applying 0.24.1-meson.patch ...
/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/temp/environment: line 1023: /0.24.1-meson.patch: No such file or directory
/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/temp/environment: line 1026: /0.24.1-meson.patch: No such file or directory
```

I tried changing

```
PATCHES=(
   "${FILES}/0.24.1-meson.patch
)
```

to

```
PATCHES=(
   "${FILESDIR}/0.24.1-meson.patch
)
```

but the problem is still there. Do you have any idea why?

I got the `FILESDIR` name from `hyprland-0.22.0.ebuild`

**Comment by MrRoy** [comment]
My mistake, it's indeed `"${FILESDIR}"`
Make sure to run `ebuild <ebuild> clean` in between changes to the ebuild.

**Comment by ignamartinoli** [comment]
Alright (luckily I learned a lot of things), now this is weirder:

```
>>> Preparing source in /var/tmp/portage/gui-wm/hyprland-0.24.1-r1/work/Hyprland-0.24.1 ...
 [32m*[0m Applying 0.24.1-meson.patch ...
patching file protocols/meson.build
Hunk #1 FAILED at 31.
1 out of 1 hunk FAILED -- saving rejects to file protocols/meson.build.rej
[A[179C [34;01m[ [31;01m!![34;01m ][0m
 [31;01m*[0m ERROR: gui-wm/hyprland-0.24.1-r1::guru failed (prepare phase):
 [31;01m*[0m   patch -p1  failed with /var/tmp/portage/gui-wm/hyprland-0.24.1-r1/files/0.24.1-meson.patch
 [31;01m*[0m 
 [31;01m*[0m Call stack:
 [31;01m*[0m               ebuild.sh, line  136:  Called src_prepare
 [31;01m*[0m             environment, line 2286:  Called default
 [31;01m*[0m      phase-functions.sh, line  872:  Called default_src_prepare
 [31;01m*[0m      phase-functions.sh, line  948:  Called __eapi8_src_prepare
 [31;01m*[0m             environment, line  383:  Called eapply '--' '/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/files/0.24.1-meson.patch'
 [31;01m*[0m             environment, line 1091:  Called _eapply_patch '/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/files/0.24.1-meson.patch'
 [31;01m*[0m             environment, line 1029:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/gui-wm/hyprland-0.24.1-r1/files/0.24.1-meson.patch'
 [31;01m*[0m   isolated-functions.sh, line  112:  Called die
 [31;01m*[0m The specific snippet of code:
 [31;01m*[0m   		die "$@"
 [31;01m*[0m 
 [31;01m*[0m If you need support, post the output of `emerge --info '=gui-wm/hyprland-0.24.1-r1::guru'`,
 [31;01m*[0m the complete build log and the output of `emerge -pqv '=gui-wm/hyprland-0.24.1-r1::guru'`.
 [31;01m*[0m The complete build log is located at '/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/temp/build.log'.
 [31;01m*[0m The ebuild environment file is located at '/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/temp/environment'.
 [31;01m*[0m Working directory: '/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/work/Hyprland-0.24.1'
 [31;01m*[0m S: '/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/work/Hyprland-0.24.1'
```

Is the error message `saving rejects to file protocols/meson.build.rej`? That's a bit cryptic

**Comment by MrRoy** [comment]
This failure is because the patch failed to apply.
How did you generate it? If you changed the source by cloning the repo, make sure you checked out the good version, otherwise your patch will be generated from master, and there can be differences between master and the tag in question (0.24.1 in this case)

**Comment by ignamartinoli** [comment]
To begin the process anew I basically

1. cleaned the ebuild
2. locally deleted the project
3. cloned again my repositoy and the PR branch
4. updated the `Manifest`
5. tried to merge

```
sicro@sicro ~/Code/Git/guru/gui-wm/hyprland $ ebuild hyprland-0.24.1-r1.ebuild clean
sicro@sicro ~/Code/Git $ rm -rf guru
sicro@sicro ~/Code/Git $ git clone https://github.com/ignamartinoli/guru -b fix-hyprland-missing-files guru
sicro@sicro ~/Code/Git/guru/gui-wm/hyprland $ ebuild hyprland-0.24.1-r1.ebuild manifest
sicro@sicro ~/Code/Git/guru/gui-wm/hyprland $ ebuild hyprland-0.24.1-r1.ebuild merge
```

The files are the same as this PR Commits.

**Comment by MrRoy** [comment]
I mean the patch, how did you create `0.24.1-meson.patch` file?

**Comment by ignamartinoli** [comment]
Aaah. I followed [this](https://wiki.gentoo.org/wiki/Creating_a_patch) manual entry until [this](https://wiki.gentoo.org/wiki/Creating_a_patch#Create_diff_using_git) section.
Basically I copy-pasted the output of `git diff | tee /tmp/foobar.patch`

**Comment by MrRoy** [comment]
Ok, I tried your patch locally and the problem is you generated your patch from Hyprland-master
In your git repo, checkout the v0.24.1 tag, then re-do your changes. After that, re-create the patch, and it should apply properly in the ebuild

**Comment by ignamartinoli** [comment]
Could you please help me with the `git` commands?
I tried `git checkout tags/v0.24.1` on my local repo on branch `fix-hyprland-missing-files` and it failed.

**Comment by MrRoy** [comment]
`git rebase tags/v0.24.1` should work

**Comment by MrRoy** [comment]
Actually, it might not since your commit doesn't apply on top on 0.24.1
I might be faster to just re-do your changes, eg. un-do your commit `git reset HEAD~1`, then undo your changes `git restore meson.build` and finally `git checkout v0.24.1`

**Comment by ignamartinoli** [comment]
I don't have any meson.build file in `guru/gui-wm/hyprland`.

Maybe it would be easier to just reopen the PR and begin anew by forking etc, right?

**Comment by MrRoy** [comment]
> Actually, it might not since your commit doesn't apply on top on 0.24.1 I might be faster to just re-do your changes, eg. un-do your commit `git reset HEAD~1`, then undo your changes `git restore meson.build` and finally `git checkout v0.24.1`

I meant to do this in the Hyprland repo. Is that how you generated the patch?

**Comment by MrRoy** [comment]
`git clone https://github.com/hyprwm/Hyprland.git`
`cd Hyprland`
`git checkout v0.24.1`
\<do changes to meson.build>
`git diff > 0.24.1-meson.patch`

**Comment by ignamartinoli** [comment]
I generated it by running

```
ebuild $(portageq get_repo_path / guru)/gui-wm/hyprland/hyprland-0.24.1.ebuild clean unpack
cd /var/tmp/portage/gui-wm/hyprland-0.24.1/work/hyprland-0.24.1-build
git init
git add .
git commit -m "Initial commit"
<editing>
git diff | tee /tmp/foobar.patch
```

**Comment by ignamartinoli** [comment]
Aaaah, I followed the manual step by step. I guess I got it wrong

**Comment by MrRoy** [comment]
Oh, I'm not familiar with the manual. I usually just clone the repositories that I want to patch directly, I wasn't aware that was a thing.

**Comment by ignamartinoli** [comment]
This is the article I followed: https://wiki.gentoo.org/wiki/Creating_a_patch

I'm correcting it now and then pushing

**Comment by ignamartinoli** [comment]
Alright. I run the commands

> `git clone https://github.com/hyprwm/Hyprland.git`
> `cd Hyprland`
> `git checkout v0.24.1`
> <do changes to meson.build>
> `git diff > 0.24.1-meson.patch`

Then I put the 0.24.1-meson.patch file into the `files/` directory of my `guru` fork.

I checked the `0.24.1-meson.patch` file and it is exactly the same as it was before, even tho I generated it from upstream. Is it normal?

**Comment by MrRoy** [comment]
Ok, I tried your pull request locally, and the patch works, however the ebuild needs a few improvements;
- Like we already discussed, the "${FILES} needs to be changed to "${FILESDIR}, also that line is missing a closing quote " at the end
- The tabulation for that line is 3 spaces and `pkgcheck` doesn't like that. Use an actual tabulation and it should satisfy `pkgcheck` :)
- Make sure to update the Manifest, by running `ebuild <file> digest` (I think you already did that but did not push it to this PR)

Despite the fact that the patch works, the compilation is failing for me, but I'm not sure why:
`protocols/meson.build:41:1: ERROR: File protocols/hyprland-toplevel-export-v1.xml does not exist.`

Can you try to merge the ebuild without the patch, just the added line in `src_unpack` ? Maybe the patch is not needed after all

**Comment by ignamartinoli** [comment]
The first problem got already solved [here](https://github.com/gentoo/guru/pull/93/files#diff-4061bd92a8d3924ea4885a49fbff796c53663a69d11ddcf91c57d60eab4db685).

I just pushed a fix for the second problem.

Now I'm looking into the third bullet point

**Comment by ignamartinoli** [comment]
Now I ran `ebuild hyprland-0.24.1-r1.ebuild digest` and pushed

**Comment by MrRoy** [comment]
Thanks. Have you tried to merge this ebuild without the patch to see if it solves your problem?

**Comment by ignamartinoli** [comment]
Alright, so I ran

```
sicro@sicro ~/Code/Git/guru/gui-wm/hyprland $ mv files/0.24.1-meson.patch ~/
sicro@sicro ~/Code/Git/guru/gui-wm/hyprland $ ebuild hyprland-0.24.1-r1.ebuild clean
sicro@sicro ~/Code/Git/guru/gui-wm/hyprland $ doas ebuild hyprland-0.24.1-r1.ebuild manifest
sicro@sicro ~/Code/Git/guru/gui-wm/hyprland $ doas ebuild hyprland-0.24.1-r1.ebuild merge
```

On the last command it fails with error

```
/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/temp/environment: line 1023: /var/tmp/portage/gui-wm/hyprland-0.24.1-r1/files/0.24.1-meson.patch: No such file or directory
/var/tmp/portage/gui-wm/hyprland-0.24.1-r1/temp/environment: line 1026: /var/tmp/portage/gui-wm/hyprland-0.24.1-r1/files/0.24.1-meson.patch: No such file or directory
```

After removing also the line

```
PATCHES=(
	"${FILESDIR}/0.24.1-meson.patch"
)
```

I do the steps mentioned before again and at first it seems to go fine, then I again get the message 

```
protocols/meson.build:41:1: [1;31mERROR:[0m File /usr/share/protocols/hyprland-global-shortcuts-v1.xml does not exist.
```

I guess the patch is necessary, right?

**Comment by MrRoy** [comment]
With the patch does the package build for you?

**Comment by ignamartinoli** [comment]
Do you mean, putting the `0.24.1-meson.patch` file again inside `gui-wm/hyprland/files` without the

```
PATCHES=(
	"${FILESDIR}/0.24.1-meson.patch"
)
```

line in the ebuild? Or with that snippet included?

**Comment by MrRoy** [comment]
Yes, with the snippet

**Comment by ignamartinoli** [comment]
> Thanks. Have you tried to merge this ebuild without the patch to see if it solves your problem?

I also put the file `0.24.1-meson.patch` back into the `files` directory? Right?

**Comment by MrRoy** [comment]
> I also put the file `0.24.1-meson.patch` back into the `files` directory? Right?

Yes

**Comment by ignamartinoli** [comment]
Now I'm at the same state as this PR currently is. After `ebuild clean`, `ebuild manifest` and `ebuild merge` the result is 

```
protocols/meson.build:41:1: ERROR: File /usr/share/protocols/hyprland-global-shortcuts-v1.xml does not exist.
```

**Pull request closed without merging**
