### PR TITLE
dev-util/bash-language-server: update SRC_URI

### PR DESCRIPTION
**Pull request by xz-dev**

### CODE REVIEW

**Comment by MrRoy** [comment]
Please sign-off your commit
Also this should be revbumped unless the package is just broken and uninstallable without this?

CC: @tastytea

**Comment by tastytea** [comment]
> Please sign-off your commit Also this should be revbumped unless the package is just broken and uninstallable without this?

it is uninstallable. apparently i uploaded the deps-tarball but forgot to include it in the ebuild :facepalm:

**Comment by xz-dev** [comment]
> Please sign-off your commit Also this should be revbumped unless the package is just broken and uninstallable without this?
> 
> CC: @tastytea
> 
> Edit: no need to revbump

Thanks to remind

**Comment by tastytea** [comment]
thank you! pushed to dev

**Pull request closed without merging**
