### PR TITLE
net-wireless/remotemouse: new package

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**

### CODE REVIEW

**Comment by vitaly-zdanevich** [comment]
@stkw0 please review.

This package is important - because when mouse dies - the smartphone can be used as a backup.

**Comment by stkw0** [comment]
I already left some comments last week...

**Comment by vitaly-zdanevich** [comment]
Where?

**Comment by stkw0** [comment]
As a review. Github changed the interface, so maybe it's a bit more hidden. For me it was shown as a small square to the right in the diff tab.

**Comment by antecrescent** [comment]
> I already left some comments last week...

Maybe I'm missing something but it seems like your comments got lost somewhere.
image

**Comment by stkw0** [comment]
Weird, I still can see it. In any case, the only problematic thing was the use of a fake version number. If upstream didn't provide a version number, I think it would be more honest and correct to use a timestamp. 
The other little thing was to add rename the SRC_URI to ${P}.zip

**Comment by vitaly-zdanevich** [comment]
Done.

**Comment by stkw0** [comment]
Thanks. Could you add RESTRICT=mirror too? Given it's "all rights reserved" there is no explicit permission to redistribute distfiles.

**Comment by stkw0** [comment]
Also, why there is an executable file that is not a shell script under /etc? That's smells bad. Could that be located in /opt for example?

**Comment by vitaly-zdanevich** [comment]
Done.

**Comment by stkw0** [comment]
Seems there are a lot of missing RDEPENDs

```
 * QA Notice: Unresolved soname dependencies:
 *
 * 	/opt/remotemouse/lib/PyQt5/Qt5/lib/libQt5Network.so.5: libgssapi_krb5.so.2
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/egldeviceintegrations/libqeglfs-emu-integration.so: libQt5EglFSDeviceIntegration.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so: libQt5EglFSDeviceIntegration.so.5 libQt5EglFsKmsSupport.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/egldeviceintegrations/libqeglfs-x11-integration.so: libQt5EglFSDeviceIntegration.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/gamepads/libevdevgamepad.so: libQt5Gamepad.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/geometryloaders/libdefaultgeometryloader.so: libQt53DCore.so.5 libQt53DRender.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/geometryloaders/libgltfgeometryloader.so: libQt53DCore.so.5 libQt53DRender.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/platforms/libqeglfs.so: libQt5EglFSDeviceIntegration.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/renderers/libopenglrenderer.so: libQt53DCore.so.5 libQt53DRender.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/renderplugins/libscene2d.so: libQt53DCore.so.5 libQt53DExtras.so.5 libQt53DInput.so.5 libQt53DLogic.so.5 libQt53DQuick.so.5 libQt53DQuickScene2D.so.5 libQt53DRender.so.5 libQt5Gamepad.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/sceneparsers/libgltfsceneexport.so: libQt53DCore.so.5 libQt53DExtras.so.5 libQt53DInput.so.5 libQt53DLogic.so.5 libQt53DRender.so.5 libQt5Gamepad.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/sceneparsers/libgltfsceneimport.so: libQt53DCore.so.5 libQt53DExtras.so.5 libQt53DInput.so.5 libQt53DLogic.so.5 libQt53DRender.so.5 libQt5Gamepad.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/sqldrivers/libqsqlpsql.so: libpq.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/plugins/webview/libqtwebview_webengine.so: libQt5WebEngine.so.5 libQt5WebEngineCore.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/qml/QtQuick/Scene2D/libqtquickscene2dplugin.so: libQt53DCore.so.5 libQt53DInput.so.5 libQt53DLogic.so.5 libQt53DQuick.so.5 libQt53DQuickScene2D.so.5 libQt53DRender.so.5 libQt5Gamepad.so.5
 * 	/opt/remotemouse/lib/PyQt5/Qt5/qml/QtQuick/Scene3D/libqtquickscene3dplugin.so: libQt53DAnimation.so.5 libQt53DCore.so.5 libQt53DInput.so.5 libQt53DLogic.so.5 libQt53DRender.so.5 libQt5Gamepad.so.5
 *
```

**Comment by vitaly-zdanevich** [comment]
But this software already have these dependencies vendored?

**Comment by vitaly-zdanevich** [comment]
I started filling RDEPEND, finding packages through https://portagefilelist.de but it is a lot of dependencies, I feel that we do not need them - because this software already works for me without installing them.

**Comment by vitaly-zdanevich** [comment]
For example

> /opt/remotemouse/lib/PyQt5/Qt5/plugins/sqldrivers/libqsqlpsql.so: libpq.so.5

Do I need to add to `RPEDEND` dev-db/postgresql??

**Comment by stkw0** [comment]
Yes. They seems to bundle the whole PyQt5 with all functionality enabled. Is there some test suite that allows to unbundle those libraries with a certain degree of security that it won't produce any runtime problems?

As a personal opinion, you don't closed source software like this to control your computer mouse with your phone. You could use for example kdeconnect (already packaged in Gentoo), maybe that solves your problem easily than adding a new hard-to-maintain ebuild.

**Comment by vitaly-zdanevich** [comment]
> kdeconnect

Hmm, is it not only for KDE? I am on i3wm. Yep free is better, thanks.
image

**Pull request closed without merging**
