### PR TITLE
dev-ml/ollama: Store version information

### PR DESCRIPTION
**Pull request by eugene-bright**
Related forum issue:
https://forums.gentoo.org/viewtopic-p-8831646.html?sid=d435fd3a93e8a4e65b6bd4335913d95f

### CODE REVIEW

**Comment by eugene-bright** [comment]
Now the version is stored in the binary and reported correctly:

```
$ ollama --version
Warning: could not connect to a running Ollama instance
Warning: client version is 0.1.47-0-g123a722
```

**Comment by eugene-bright** [comment]
@MrRoy Please take a look

**Comment by vitaly-zdanevich** [comment]
Merged, thanks f0eb17f

Next time you can mention maintainer from metadata.xml

`Closes` does not automatically close this PR, what is the correct syntax?

**Review by vitaly-zdanevich — APPROVED** [review]

**Comment by eugene-bright** [comment]
You merged to `dev` and this is pointed to `master`. Pushing to the `master` would have cause PR closure

**Comment by antecrescent** [comment]
>> Merged, thanks [f0eb17f](https://github.com/gentoo/guru/commit/f0eb17f75400cdea0262eadf2b3ba90425b9d29f)
>>
>> Next time you can mention maintainer from metadata.xml

Alternatively, file a bug (optionally with a patch) on bugs.gentoo.org where it'll get assigned correctly by the bug wranglers.
>> `Closes` does not automatically close this PR, what is the correct syntax?

> You merged to `dev` and this is pointed to `master`. Pushing to the `master` would have cause PR closure

@vitaly-zdanevich's closure of this PR was correct, since pushing directly to `master` is not allowed. The PR would have been closed once the closing commit had been reviewed and merged into `master` by a TC.

**Pull request closed without merging**
