### PR TITLE
Update repoman.yml

### PR DESCRIPTION
**Pull request by scardracs**
Updated portage to latest available

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Looks good to me :+1: 

I wonder if it would be possible to have this always fetch the latest version, that way we won't have to touch it every time there is a new version of repoman.

(as a side note, if you want to run the GitHub Actions checks against this PR than you'll have to make the PR against the dev branch instead of the master branch)

**Comment by scardracs** [comment]
> Looks good to me +1
> 
> I wonder if it would be possible to have this always fetch the latest version, that way we won't have to touch it every time there is a new version of repoman.
> 
> (as a side note, if you want to run the GitHub Actions checks against this PR than you'll have to make the PR against the dev branch instead of the master branch)

Yeah I know that (I mean about your side note), but this isn't actually a PR for an ebuild, so I thought I have to PR directly inside master

**Comment by AndrewAmmerlaan** [comment]
> Yeah I know that (I mean about your side note), but this isn't actually a PR for an ebuild, so I thought I have to PR directly inside master. I'm sorry if I have make it wrong

Non-ebuild contributions also go through dev first (otherwise the branches would diverge). You can just commit/PR this just as you would with an ebuild :)

**Comment by scardracs** [comment]
> > Yeah I know that (I mean about your side note), but this isn't actually a PR for an ebuild, so I thought I have to PR directly inside master. I'm sorry if I have make it wrong
> 
> Non-ebuild contributions also go through dev first (otherwise the branches would diverge). You can just commit/PR this just as you would with an ebuild :)

Ok then :). Also I may suggest for you first point to set a "default" portage version and run an action to update it directly from gentoo. This will take surely more time, but we are sure to run repoman against latest version available

**Pull request closed without merging**
