### PR TITLE
fix Manifest

### PR DESCRIPTION
**Pull request by SetOfAllSets**
Can't install without manually editing the manifest to match what I am showing in this repo. Installing with this modified manifest yields a fully working installation.

### CODE REVIEW

**Comment by N-R-K** [comment]
We'd need to investigate why the hash changed to begin with because it's not a normal thing to happen (see https://github.com/gentoo/guru/pull/95#issuecomment-1528969073).

**Comment by N-R-K** [comment]
ping: @freijon

**Comment by freijon** [comment]
Hmm... Maybe related to https://marc.info/?l=gentoo-dev&m=170229217830070&w=2 ?
I recently had a bug filed about this and fixed it, but maybe Codeberg did some further changes? It doesn't look like upstream changed anything, they still use the same 7 months old tag for the latest release.

**Comment by N-R-K** [comment]
> maybe Codeberg did some further changes

If you can confirm that's the case then we should file a bug to codeberg directly. https://codeberg.org/Codeberg/Community/issues

**Comment by freijon** [comment]
Saw your edit too late...

I did some investigating:
I compared my archive from `/var/cache/distfile` (which still matches the `sha512sum` of the Manifest) with the current release archive from Codeberg (which now has a different checksum and matches with the ones from this PR). Result:
When both archives are uncompressed and `sha512sum` is run on the uncompressed tarball, both have the same checksum. 

Conclusions:
- Codeberg changed their compression method *again*!
- The PR seems safe to merge

**Comment by MrRoy** [comment]
@SetOfAllSets can you squash your commits, and also sign it off? See https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

**Comment by SetOfAllSets** [comment]
> @SetOfAllSets can you squash your commits, and also sign it off? See https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

My email contains my full legal name and as such I would not be comfortable doing so, I'd be gine with someone else making a similar commit however.

**Comment by MrRoy** [comment]
> > @SetOfAllSets can you squash your commits, and also sign it off? See https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin
> 
> My email contains my full legal name and as such I would not be comfortable doing so, I'd be fine with someone else making a similar commit however.

Is it fine if I use your git config username + github anonymous email (Author: Velma <98566029+SetOfAllSets@users.noreply.github.com>), or do you prefer just "SetOfAllSets" with no email at all?

**Comment by SetOfAllSets** [comment]
> > > @SetOfAllSets can you squash your commits, and also sign it off? See https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin
> > 
> > 
> > My email contains my full legal name and as such I would not be comfortable doing so, I'd be fine with someone else making a similar commit however.
> 
> Is it fine if I use your git config username + github anonymous email (Author: Velma [98566029+SetOfAllSets@users.noreply.github.com](mailto:98566029+SetOfAllSets@users.noreply.github.com)), or do you prefer just "SetOfAllSets" with no email at all?

Oh! I didn't know that email existed! I can do it myself if I can do it without revealing my email, thank you.

**Comment by MrRoy** [comment]
And please use standard git messages (example: gui-apps/fuzzel: update manifest)
You can use [pkgdev](https://wiki.gentoo.org/wiki/Pkgdev) to automatically set the commit messages

**Comment by SetOfAllSets** [comment]
> [98566029+SetOfAllSets@users.noreply.github.com](mailto:98566029+SetOfAllSets@users.noreply.github.com)

Done and done

**Comment by SetOfAllSets** [comment]
> And please use standard Gentoo git messages (example: gui-apps/fuzzel: update manifest) You can use [pkgdev](https://wiki.gentoo.org/wiki/Pkgdev) to automatically set the commit messages

Done and done

**Comment by MrRoy** [comment]
Missing sign-off :)

**Comment by SetOfAllSets** [comment]
> Missing sign-off :)

Oop! I accidentally made it only sign off on the official gentoo repo, how silly of me, one sec.

**Comment by SetOfAllSets** [comment]
done

**Comment by SetOfAllSets** [comment]
closed? what?

**Comment by MrRoy** [comment]
> closed? what?

Since GitHub is a mirror of Gentoo's git repository, PRs aren't merged directly, but your contribution was merged, see commit a26b4c839e8ce5880ff3a1bce3d0e5176e07bab4

By the way, if you want to contribute more to GURU, you can get access to commit directly to the dev branch if you follow the guide here: https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors (the wiki is a little outdated, you do not have to use your real name anymore)

**Comment by SetOfAllSets** [comment]
> > closed? what?
> 
> Since GitHub is a mirror of Gentoo's git repository, PRs aren't merged directly, but your contribution was merged, see commit [a26b4c8](https://github.com/gentoo/guru/commit/a26b4c839e8ce5880ff3a1bce3d0e5176e07bab4)
> 
> By the way, if you want to contribute more to GURU, you can get access to commit directly to the dev branch if you follow the guide here: https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors (the wiki is a little outdated, you do not have to use your real name anymore)

Ah ok, If I start commiting frequently (this is my first commit in all my years of using gentoo, so not sure how likely that is) I will follow the guide, Thanks

**Comment by n0toose** [comment]
> EDIT: Looks like an issue already exists for this: https://codeberg.org/Codeberg/Community/issues/1366

> Codeberg changed their compression method again!

Hi, I think it's safe to say that it's absolutely regretful that this regression happened in the first place. A "hack" was implemented to prevent future regressions *in the future* a few weeks ago, but, unfortunately, issues with packages that were created before that fix was implemented are to be expected.

I don't know much about the fix, but the current standing is there should have been no change. If a change took place, it is a big problem and completely unintentional and we'll need the following:

> There has been no further change on our end. [We need] a detailed description of which checksum changed between which values [... and] when the checksum was created.

**Comment by N-R-K** [comment]
> Codeberg changed their compression method again!

Turns out they didn't "change" the tarball. Their "fix" of the issue reverted the tarball back to the original state.

In other words, this PR/patch basically reverts the hash back to what it was:
https://github.com/gentoo/guru/commit/a26b4c839e8ce5880ff3a1bce3d0e5176e07bab4
https://github.com/gentoo/guru/commit/8b748050a20c9d216e33c3a8d5017429159a4b5d

**Pull request closed without merging**
