### PR TITLE
*/*: fix variable order

### PR DESCRIPTION
**Pull request by antecrescent**
I manually went through some entries for `pkgcheck scan -c VariableOrderCheck`.
I'll keep pushing commits by category, feel free to merge this whenever.

### CODE REVIEW

**Comment by antecrescent** [comment]
I sometimes applied other small fixes. :
- replace `$var` with `${var}`
- `EbuildUnquotedVariablesCheck`
- remove variable self-assignments
- remove redundant phase functions (`dev-python/undervolt`, `dev-util/tflint-bin`)
- add `QA_PREBUILT` for `dev-util/tflint-bin`
-...

Since I already lost track of all these miscellaneous changes, I'll go over my changes again and split them out into separate commits. Please wait, before merging this PR.

**Comment by MrRoy** [comment]
Looks like there are conflicts now, can you check them?

**Comment by antecrescent** [comment]
This should do it. Thanks for the ping!

**Comment by stkw0** [comment]
You plan to add any further commits? I guess touching so many files would produce more conflicts if this PR is left for too much time without being merge.

**Comment by antecrescent** [comment]
> You plan to add any further commits?

Yes, I want to fix the whole repo. (278 ebuilds to go; this should and could probably be automated)
>  I guess touching so many files would produce more conflicts if this PR is left for too much time without being merge.

Yes, I'd prefer merging these changes in batches, instead of waiting for the rest :')

**Comment by MrRoy** [comment]
@antecrescent if this ready to merge, then? If not, could you change this PR to a draft until it is?

**Comment by antecrescent** [comment]
> @antecrescent is this ready to merge, then?

Yes, please merge it. There might have been a miscommunication..

In an earlier comment (https://github.com/gentoo/guru/pull/170#issuecomment-2099653348), I intended to say that I do plan to fix the variable order for all ebuilds in ::guru, but that I will do so in separate PRs to avoid the need for constant rebases and to keep the work of reviewing manageable.

Thank you for keeping an eye on the PR!

**Comment by MrRoy** [comment]
@antecrescent ok perfect, then I will merge this.
Thanks for your work! :)

**Pull request closed without merging**
