### PR TITLE
some ebuilds i made and a version bump(lux, pamixer, and version bump…

### PR DESCRIPTION
**Pull request by oblivikun**
… nuclear-bin)

### CODE REVIEW

**Comment by MrRoy** [comment]
Please follow the [Gentoo git workflow](https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_policy) & [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html)

Particularly:
- Atomicity
- Commit message format
- Sign-off your commit

**Comment by MrRoy** [comment]
Hi @oblivikun,

Do you still want this to be merged?
If so please review my above comment
In short;
- Your commits need to be split up (one commit per package affected)
- Your commit messages should indicate which packages are being touched
- Your commits need to be signed off (using `git commit --signoff`)

**Comment by oblivikun** [comment]
I am so sorry i dont read my github notifications alot. Is this good?

**Comment by oblivikun** [comment]
added oksh

**Comment by MrRoy** [comment]
Hi @oblivikun,

You have two commits which aren't signed-off, can you please sign them off? Afterwards I'll be able to merge this

**Comment by oblivikun** [comment]
oh uh oops(i cannot use git im so sorry)

**Pull request closed without merging**
